version: "3.8"

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    image: mqtt-relay:latest
    container_name: mqtt-relay
    restart: unless-stopped
    ports:
      - "${RELAY_HOST_PORT:-8080}:8080"
    environment:
      MQTT_URL: ${MQTT_URL}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      MQTT_SUB_TOPIC: ${MQTT_SUB_TOPIC:-drone/+/events}
      # If you mount a CA file below, also set:
      # MQTT_CAFILE: /ca.crt
      # HTTP_PORT: "8080"
    # Uncomment the volume and MQTT_CAFILE env above if your broker uses a custom CA
    # volumes:
    #   - ${MQTT_CAFILE_HOST}:/ca.crt:ro

